### Problem 1
If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.

Find the sum of all the multiples of 3 or 5 below 1000.

In [ ]:
multiples = []
for n in range(1, 1000):
    if n%3 == 0 or n%5 == 0:
        multiples.append(n)
sum(multiples)

233168

### Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

In [ ]:
fibonacci = [1, 2]
while fibonacci[-1]<4000000:
    add = fibonacci[-1] + fibonacci[-2]
    fibonacci.append(add)
evens = []
for n in fibonacci:
    if n%2 == 0:
        evens.append(n)
sum(evens)

4613732

### Problem 3
The prime factors of 13195 are 5, 7, 13 and 29.

What is the largest prime factor of the number 600851475143 ?

In [ ]:
divisors = []
num = 600851475143
for n in range(2, 1000000):
    if num%n == 0:
        num = num/n
        divisors.append(n)
print(divisors[-1])

6857

### Problem 4
A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 Ã— 99.

Find the largest palindrome made from the product of two 3-digit numbers.

In [ ]:
numbers = [n for n in range(100, 1000)]
multiples = [n*m for n in numbers for m in numbers]
palindromes = [num for num in multiples if str(num) == str(num)[::-1]]
print(max(palindromes))

906609

In [ ]:
numbers = [n for n in range(100, 1000)]
multiples = []
palindromes =[]

for n in numbers:
    for m in numbers:
        multiples.append(n*m)
        
for num in multiples:
    num_string = str(num)
    if num_string == num_string[::-1]:
        palindromes.append(num)
print(max(palindromes))

906609

### Problem 5
2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.

What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?

In [2]:
numbers = [n for n in range(1, 21)]

In [3]:
numbers = [n for n in range(1, 21)]
numbers.remove(1)
print(numbers)

[2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

### Problem 6
<p>The sum of the squares of the first ten natural numbers is,</p>
$$1^2 + 2^2 + ... + 10^2 = 385$$
<p>The square of the sum of the first ten natural numbers is,</p>
$$(1 + 2 + ... + 10)^2 = 55^2 = 3025$$
<p>Hence the difference between the sum of the squares of the first ten natural numbers and the square of the sum is $3025 - 385 = 2640$.</p>
<p>Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum.</p>

In [ ]:
numbers = list(range(1, 101))
squares = [num**2 for num in numbers]
print(sum(numbers)**2-sum(squares))

25164150

### Problem 7
<p>By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is 13.</p>
<p>What is the 10 001st prime number?</p>